export const CACHE_TIMES = {
  STATISTICS: 1000 * 60 * 5,
}

export const TOAST_DURATIONS = {
  RECORD_NOTIFICATION: 60000,
}

export const TIME_UNITS = {
  MILLISECONDS_IN_SECOND: 1000,
  SECONDS_IN_MINUTE: 60,
  MINUTES_IN_HOUR: 60,
}
