version: '3'
services:
  app:
    build: .
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URL=file:./dev.db
      - NUXT_AUTH_SECRET=your-secret-key
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}