version: '3.8'
services:
  app:
    build: .
    ports:
      - '3030:3030'
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    volumes:
      - ./prisma:/app/prisma
      - ./.env:/app/.env
